export const ReducerTypes = {
    GET_TRENDING_REPOSITORIES: 'GET_TRENDING_REPOSITORIES',
    GET_REPOSITORY_SEARCH_LIST: 'GET_REPOSITORY_SEARCH_LIST',
    GET_REPOSITORY_DETAILS: 'GET_REPOSITORY_DETAILS'
}